version: "3"
services: 
    product-app:
        container_name: product-app
        image: latest123/product-app
        restart: always
        build: .
        command: "node app.js"
        ports:
            - "8080:8080"
        links: 
            - mongo
    
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27017:27017"